name: profile

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: profile
    steps:
      - uses: actions/checkout@v3
      - uses: federicopfund/profile@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name federicopfund
          git config user.email federicopfund@gmail.com
          git add -A .
          git commit -m "generated"
          git push
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
